### ISSUE TITLE
cant create network via terraform

### ISSUE THREAD

**Issue by TheBelgarion** [bpg/terraform-provider-proxmox#679] opened 2023-11-04 10:01 UTC
**Describe the bug**
I tried to create a simple bridge via terraform but getting the error message
```
 Could not create Linux Bridge, unexpected error: failed to create network interface "vmbr3" for node "proxmox": received an HTTP 501 response - Reason:
│ Method 'POST /api2/json/nodes/proxmox/network' not implemented
```

**To Reproduce**

```hcl
resource "proxmox_virtual_environment_network_linux_bridge" "vmbr3_bridge" {
  provider  = proxmox-bpg
  name      = "vmbr3"
  node_name = "proxmox"
  ports     = ["enp5s0"]       # Add the network interface that you want to attach to the bridge
  address   = "192.168.3.0/24" # Add the desired IP address and subnet mask
  comment = "@TF:network range for k3s cluster nodes"
}

provider "proxmox-bpg" {
  endpoint  = local.PM_API_URI
  api_token = local.API_TOKEN
  insecure  = true
  ssh {
    agent    = true
    username = "api"
  }
}
```

im quite sure there URI and Token are correct but i dont thing it event gets to the machine because i dont see any log there.
also just checked apit has all permissions currently because it really hard to debug which onces a needed in some case - so should not be a permission problem.

so probably the error message is misleading and should rather say if it cant login or something.

Please also provide a minimal Terraform configuration that reproduces the issue.

**Expected behaviour**
clear error message or some kind of debug mode would be nice

**Screenshots**

**Additional context**
-single proxmox
- provider 0.37.0

**Comment by bpg** [comment] 2023-11-06 03:11
Hi @TheBelgarion!

Could you please double check the PVE endpoint, and if it includes path '/api2/json' then remove it and try again?

**Comment by bpg** [comment] 2023-12-20 02:58
Unable to reproduce on v0.41.0, and no author response received, so closing. 
Feel free to reopen with new details.

**Closed by bpg** 2023-12-20 02:58 UTC
Labels: :bug: bug, :hourglass: pending author's response
