### ISSUE TITLE
Not able to clone from a template (cloud-init) on Proxmox 8.2.7

### ISSUE THREAD

**Issue by rangalo** [bpg/terraform-provider-proxmox#1601] opened 2024-10-25 08:10 UTC
**Describe the bug**
I am trying to clone a template based on cloud-init and created from cloud image. 

`terraform plan ` 

succeeds. 

While `terraform apply` fails with the message. 

`Error: unable to retrieve the next available VM identifier: context deadline exceeded`

**To Reproduce**

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl

terraform {
  required_version = ">=1.5.7"

  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = ">=0.66.2"
    }
  }
}

provider "proxmox" {
  endpoint = var.pve_url

  # api_token="token_id=token_secret"
  api_token = "${var.token_id}=${var.token_secret}"

  # leave tls_insecure set to true unless you have your proxmox SSL certificate situation fully sorted out (if you do, you will know)
  insecure = true
}



resource "proxmox_virtual_environment_vm" "k8s_master" {

  count       = var.master_count
  name        = "k8s_m${count.index + 1}" # count.index starts at 0, so + 1 means this VM will be named k8sn1 in proxmox
  node_name   = var.proxmox_node
  description = "K3s master node"
  tags        = ["terraform", "k3s", "homelab"]
  on_boot     = true

  clone {
    vm_id = 1003
    full  = true
  }

  agent {
    enabled = true
  }

  cpu {
    cores = 1
  }

  memory {
    dedicated = 2048
  }

  network_device {
    bridge = "vmbr0"
  }

  # cloud-init config 
  initialization {

    user_account {
      keys = ["${var.ssh_key}"]
    }

    ip_config {
      ipv4 {
        address = "192.168.178.24${count.index + 1}"
      }
    }
  }
}

```

**Expected behavior**
2 VMs should be created in proxmox

**Screenshots**
![image](https://github.com/user-attachments/assets/2639dd4b-0c1a-4a6f-9342-0dce0fa23384)

**Additional context**

- Single or clustered Proxmox: Single
- Proxmox version: 8.2.7
- Provider version (ideally it should be the latest version):
- Terraform/OpenTofu version: Terraform 1.9.8
- OS (where you run Terraform/OpenTofu from): Archlinux 
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by arsensimonyanpicsart** [comment] 2024-10-26 09:29
I can confirm, and here is the sample code

code to reproduce
```
provider "proxmox" {
  endpoint  = "https://xxx:8006/"
  api_token = "xxx"
  insecure  = true
}

resource "proxmox_virtual_environment_vm" "vm1" {
  name            = "va-vm-name1"
  node_name       = "va-dev-proxmox01"
  stop_on_destroy = true

  clone {
    vm_id     = 9001
    full      = true
    node_name = "va-dev-proxmox02"
  }
}

resource "proxmox_virtual_environment_vm" "vm2" {
  name            = "va-vm-name2"
  node_name       = "va-dev-proxmox01"
  stop_on_destroy = true

  clone {
    vm_id     = 9001
    full      = true
    node_name = "va-dev-proxmox02"
  }
}
```

and here is the output
```
proxmox_virtual_environment_vm.vm1: Creating...
proxmox_virtual_environment_vm.vm2: Creating...
proxmox_virtual_environment_vm.vm2: Still creating... [10s elapsed]
proxmox_virtual_environment_vm.vm2: Creation complete after 18s [id=115]
╷
│ Error: unable to retrieve the next available VM identifier: context deadline exceeded
│
│   with proxmox_virtual_environment_vm.vm1,
│   on main.tf line 16, in resource "proxmox_virtual_environment_vm" "vm1":
│   16: resource "proxmox_virtual_environment_vm" "vm1" {
```
i will be glad to provide any info that will help the investigation.

**Comment by rangalo** [comment] 2024-10-28 07:33
@bpg  Your assumption seems to be correct. For the time datasource, I am getting the connection timeout error. See the screenshot. 

Strange thing is that the proxmox server is accessible from the same computer using a browser. 

![image](https://github.com/user-attachments/assets/f07efc7e-6eb5-456a-a86a-f93438a35967)

**Comment by bpg** [comment] 2024-10-29 18:59
> Strange thing is that the proxmox server is accessible from the same computer using a browser.

@rangalo is it possible that browser is going through proxy, or other way around, you have an HTTP_PROXY environment variable defined in your shell session running Terraform?

**Comment by rangalo** [comment] 2024-10-29 20:13
No. Telnet also works from the command line

**Comment by bpg** [comment] 2024-10-30 14:02
Hey @arsensimonyanpicsart your issues seems to be different from the OP use case. As I see in the log the provider managed to create one VM and stumbled upon creating another. Would you mind opening a new issue, so we can discuss specifics there?

**Comment by arsensimonyanpicsart** [comment] 2024-10-30 15:19
Hello @bpg , i will be happy to do that, thanks!

**Comment by bpg** [comment] 2024-11-04 01:30
Hey @rangalo, I don’t have any clear ideas on why the provider is behaving this way. The ‘connect: connection timeout’ error is a low-level error from the standard library, indicating that a TCP connection to the specified IP and port failed.

This makes me suspect there may be a proxy, firewall, or some other network filter on the network path to PVE that blocks the connection. Alternatively, it could be something at the OS level, like SELinux or a local SEIM agent interfering.

I’d recommend investigating along those lines. Try sending requests to the PVE endpoint using curl, e.g. `curl -v -k https://<PVE IP>:8006/api2/json/access/ticket`, or even dig deeper by capturing traffic with tcpdump or Wireshark. That might provide some clues.

**Comment by rangalo** [comment] 2024-11-04 10:33
Curl call to the api seems to work. See the screenshot. 

![image](https://github.com/user-attachments/assets/17069ee0-5385-4365-a45c-bed2d6b1fbbc)

**Comment by rangalo** [comment] 2024-11-04 10:56
Is there any way to debug how the provider is passing credentials (api token and api secret) to the server? It seems that if the tokenId is wrong or not provided, the server will respond with connection error rather than authentication failure.  

See.. 

![image](https://github.com/user-attachments/assets/19c77649-8861-4a97-8ec3-74dfc6de9fb8)

**Comment by rangalo** [comment] 2024-11-06 13:31
**UPDATE:**

It seems that the problem was my backend. 
I was using [Terraform Cloud](https://app.terraform.io) as backend. 

When I looked at the traffic using wireshark, it wasn't even reaching the proxmox server. It was calling the backend in some infinite loop. 

When I switched to local and also s3 backend, the provider started working.

**Comment by bpg** [comment] 2024-11-26 01:23
> When I looked at the traffic using wireshark, it wasn't even reaching the proxmox server. It was calling the backend in some infinite loop.
>
> When I switched to local and also s3 backend, the provider started working.
>
> I think this is still a bug.

Not sure how the provided could be involved in this scenario, as it has nothing to do with the backend configuration.

I also don't see how missing / invalid authorization headers could cause SSL errors 🤔 
Running the same request with invalid token via curl to my PVE just returns 401 status code.

I'm going to close this ticket now, as I don't really understand what could be "fixable" on the provider's side to mitigate this situation. Feel free to re-open, or create a new ticket when you have more information.

**Closed by bpg** 2024-11-26 01:23 UTC
Labels: :bug: bug, :shrug: can't reproduce
