### ISSUE TITLE
Plugin did not respond

### ISSUE THREAD

**Issue by yfcentral** [bpg/terraform-provider-proxmox#676] opened 2023-11-03 10:29 UTC
**Describe the bug**

While creating a proxmox_virtual_environment_vm resource the bug appeared after tried few times.

**To Reproduce**
1. Create a resource '....'
```hcl
resource "proxmox_virtual_environment_vm" "template" {
  name        = "ubuntu-image"
  description = "Managed by Terraform"
  tags        = ["terraform"]
  node_name   = "pve"
  vm_id       = 500
  machine     = "i440fx" 
  bios        = "seabios"

  cpu {
    cores = 1
  }

  agent {
    enabled = true
  }

  network_device {
    bridge = "vmbr0"
  }

  disk {
    datastore_id = "local-lvm"
    file_id      = proxmox_virtual_environment_file.cloud_image.id
    interface    = "scsi0"
  }

  operating_system {
    type = "l26" # Linux Kernel 2.6 - 5.X.
  }

  initialization {
    datastore_id      = "local-lvm"
    user_account {
      keys     = var.ssh_key
      password = var.vm_pwd
      username = var.vm_usr
    }

    dns {
      server = "8.8.8.8"
    }
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    user_data_file_id = proxmox_virtual_environment_file.cloud_config.id
  }
  template = true
}

resource "proxmox_virtual_environment_vm" "srv" {
  name      = "srv"
  node_name = "pve"
  migrate   = true // migrate the VM on node change
  vm_id     = 700
  tags      = ["terraform", "ubuntu"]

  clone {
    vm_id = proxmox_virtual_environment_vm.template.id
  }

  memory {
    dedicated = 2048
  }

  initialization {
    interface = "scsi0"

    dns {
      server = "8.8.8.8"
    }
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }
}

resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "snippets"
  node_name    = "pve"

  source_file {
    path = "cloud-init/user-data.yml"
  }
}

resource "proxmox_virtual_environment_file" "cloud_image" {
  content_type = "iso"
  datastore_id = "local"
  node_name    = "pve"


  source_file {
    path      = "https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img"
    file_name = "ubuntu-22-04-amd64-20221219-1234.img"
    checksum  = "8dd2e6b5e5aad20c3f836123b300cba9861249408cbb07c359145a65d6bab6b6"
  }
}
```

2. Run '....' `terraform apply --var-file=path-to-var-file.tfvars`
3. See error
```
**_╷
│ Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin6.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵_**

Stack trace from the terraform-provider-proxmox_v0.37.0 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18b0a80]

goroutine 26 [running]:
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmReadCustom({0x1c48b48, 0xc0006a4700}, 0xc00014ea00, {0x1a1e320?, 0xc0002a0e40?}, 0x1095de5?, 0xc000681200, 0xc00069d128?)
        github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:3958 +0xcb60
github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource.vmRead({0x1c48b48, 0xc0006a4700}, 0xc00014ea00, {0x1a1e320?, 0xc0002a0e40?})
        github.com/bpg/terraform-provider-proxmox/proxmoxtf/resource/vm.go:3610 +0x791
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc00032d180, {0x1c48aa0, 0xc0006b8420}, 0xd?, {0x1a1e320, 0xc0002a0e40})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:795 +0x11b
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc00032d180, {0x1c48aa0, 0xc0006b8420}, 0xc0004156c0, {0x1a1e320, 0xc0002a0e40})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:1089 +0x552
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0000114d0, {0x1c48aa0?, 0xc0006b82d0?}, 0xc000184200)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:649 +0x48a
github.com/hashicorp/terraform-plugin-mux/tf5to6server.v5tov6Server.ReadResource({{0x1c500c0?, 0xc0000114d0?}}, {0x1c48aa0?, 0xc0006b82d0?}, 0xc0002762c0?)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5to6server/tf5to6server.go:119 +0x225
github.com/hashicorp/terraform-plugin-mux/tf6muxserver.(*muxServer).ReadResource(0x1c48ad8?, {0x1c48aa0?, 0xc0003cb440?}, 0xc0002762c0)
        github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf6muxserver/mux_server_ReadResource.go:35 +0x193
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ReadResource(0xc00025d680, {0x1c48aa0?, 0xc0003ca2a0?}, 0xc0006020c0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/tf6server/server.go:787 +0x48a
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ReadResource_Handler({0x1a96660?, 0xc00025d680}, {0x1c48aa0, 0xc0003ca2a0}, 0xc00065a000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:431 +0x169
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0002521e0, {0x1c4e670, 0xc0004029c0}, 0xc000656000, 0xc0003cad50, 0x2248d28, 0x0)
        google.golang.org/grpc@v1.57.1/server.go:1358 +0xe15
google.golang.org/grpc.(*Server).handleStream(0xc0002521e0, {0x1c4e670, 0xc0004029c0}, 0xc000656000, 0x0)
        google.golang.org/grpc@v1.57.1/server.go:1735 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        google.golang.org/grpc@v1.57.1/server.go:970 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 23
        google.golang.org/grpc@v1.57.1/server.go:981 +0x145

Error: The terraform-provider-proxmox_v0.37.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```
4. Modify the resource '....' **NONE**
5. Run '....' **NONE**
6. See error **NONE**

Please also provide a minimal Terraform configuration that reproduces the issue.

**Expected behavior**

**Screenshots**

**Additional context**
- Single or clustered Proxmox:
- Provider version (ideally it should be the latest version):
- Terraform version:
- OS (where you run Terraform from):
- Debug logs (`TF_LOG=DEBUG terraform apply`):

**Comment by bpg** [comment] 2023-11-08 03:43
Hi @yfcentral! 👋🏼 

Thanks for the report. I'm trying to reproduce this issue, but I'm seeing a bit different behaviour -- the cloned VM just failing to start due to its disk is not attached. I'll investigate further.

BTW, `machine     = "i440fx"` in your example has invalid value, and it should fail the deployment. You can use `pc` or `q35`. I've [updated](https://github.com/bpg/terraform-provider-proxmox/pull/681/files#diff-e1aef3b40d8fbb5bbef4a1743249c25e398f91ff37313a702683728e30ea4ad4R373-R375) docs (this is not released just yet).

**Comment by bpg** [comment] 2023-11-13 03:06
Hey @yfcentral, I think the issue is in template of cloned VM `srv` -- it re-defines cloud init device as `scsi0` in the `initializaiton` block, which conflicts with the existing `scsi0` disk defined in the template VM. The template's cloud init is on default `ide2`, and this can't be changed during cloning.

I'm going to close this ticket, but please feel free to reopen, comment on it if you need further assistance.

**Closed by bpg** 2023-11-13 03:06 UTC
Labels: bug
