### ISSUE TITLE
Add hostname to scaled VM's 

### ISSUE THREAD

**Issue by breakingflower** [bpg/terraform-provider-proxmox#1094] opened 2024-03-05 15:49 UTC
I'm new to terraform. Perhaps the solution is simple. 

**Is your feature request related to a problem? Please describe.**
When creating multple VM using the `count` parameter the hostname of the system is always the same. I would like to be able to use a simple hostname parameter to add the hostname programmatically, e.g.

```
resource "proxmox_virtual_environment_vm" "k8s_worker" {
  count     = var.deployment_worker_count
  name      = "${var.deployment_name}-worker-${count.index}"
   ...
  initialization {
    hostname = "${var.deployment_name}-worker-${count.index}" <-- this would be useful
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    vendor_data_file_id = proxmox_virtual_environment_file.vendor_cloud_config.id
    user_data_file_id = proxmox_virtual_environment_file.k8s_cloud_config.id
  }
```
Similar to the container instantiation [here](https://github.com/bpg/terraform-provider-proxmox/blob/991db34fe2c77a0d4eb3a465f528f6f8119fdc79/docs/resources/virtual_environment_container.md?plain=1#L22) 

This way I can automatically scale the system with non-overlapping hostnames. Especially important in k3s / k8s because they are reliant on hostnames to communicate. 

**Describe the solution you'd like**
Either an option to do this in the highest level of the resource or a way to use the name parameter in cloud-init files. 

**Describe alternatives you've considered**
I tried to use the name variable in cloud init but it is never resolving. I am not sure what I am doing wrong. I've gotten cyclic dependency issues before, e.g. when trying to infer the name from `proxmox_virtual_environment_vm.k8s_worker.name` or something similar. 

**Additional context**
Thanks for the help.

**Comment by maykopetersen** [comment] 2024-03-05 17:18
Do you use `preserve_hostname: false` in your `cloud.cfg` file?

Read more: https://cloudinit.readthedocs.io/en/latest/reference/modules.html#set-hostname

**Comment by breakingflower** [comment] 2024-03-05 18:06
That unfortunately did not change anything, the VM boots with default hostname ubuntu. 

I don't use any hostname setting. I'm not sure how I can transfer the value of this name , e.g. `k8s-worker-1`, to the cloud-init yaml files. I'm using the following setup: 
```
resource "proxmox_virtual_environment_vm" "k8s_control" {
  count     = var.deployment_control_count
  name      = "${var.deployment_name}-control-${count.index}"
 ... 

  initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    vendor_data_file_id = proxmox_virtual_environment_file.vendor_cloud_config.id
    user_data_file_id = proxmox_virtual_environment_file.k8s_cloud_config.id
  } 
```
i read the yaml files from an proxmox_virtual_environmnet_file 
```

resource "proxmox_virtual_environment_file" "k8s_cloud_config" {
    content_type = "snippets"
    datastore_id = "local"
    node_name    = var.virtual_environment_proxmox_node
    source_file {
        path = "./cloud-init/k8s-node.yaml"
    }
}

resource "proxmox_virtual_environment_file" "vendor_cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.virtual_environment_proxmox_node
  source_file {
    path = "./cloud-init/vendor.yaml"
  }
}
```
vendor.yaml 
```
#cloud-config
package_update: true
package_upgrade: true
...
runcmd:
    # base settings
    - timedatectl set-timezone Europe/Brussels
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
```
k8s-node.yaml
```
#cloud-config
runcmd:
    # Generate random hostname because hostname is not transferred from terraform
    - hostnamectl set-hostname k8s-$(openssl rand -hex 2) <-- im not sure what else to use here. 
    # It is also recommended that all managed nodes disable firewalls and swap. See K3s Requirements for more information.
    - swapoff -a 
    - ufw disable
    # post install steps
    - reboot 
```
I can't seem to find any variable I can use to substitute the hostname with. Any idea's welcome.

**Comment by maykopetersen** [comment] 2024-03-05 23:02
The VM's name in Proxmox interface will be the SAME that inside VM, which you see using `hostname` command.
I.e.: if in Proxmox your VM's name is `vm01` and you use Cloud-init, when you access your VM you'll see: `vm01`.
If it doens't happen, the problem is with you cloud-init files.
I'll put an example:
```
manage_etc_hosts: true
users:
   - default
ssh_deletekeys: true 
disable_root: true
preserve_hostname: false
apt:
   preserve_sources_list: true

# The modules that run in the 'init' stage
cloud_init_modules:
 - migrator
 - seed_random
 - bootcmd
 - write-files
 - growpart
 - resizefs
 - disk_setup
 - mounts
 - set_hostname
 - update_hostname
 - update_etc_hosts
 - ca-certs
 - rsyslog
 - users-groups
 - ssh

# The modules that run in the 'config' stage
cloud_config_modules:
 - snap
 - ssh-import-id
 - keyboard
 - locale
 - set-passwords
 - grub-dpkg
 - apt-pipelining
 - apt-configure
 - ntp
 - timezone
 - disable-ec2-metadata
 - runcmd
 - byobu

# The modules that run in the 'final' stage
cloud_final_modules:
 - package-update-upgrade-install
 - fan
 - landscape
 - lxd
 - write-files-deferred
 - puppet
 - chef
 - mcollective
 - salt-minion
 - reset_rmc
 - refresh_rmc_and_interface
 - rightscale_userdata
 - scripts-vendor
 - scripts-per-once
 - scripts-per-boot
 - scripts-per-instance
 - scripts-user
 - ssh-authkey-fingerprints
 - keys-to-console
 - install-hotplug
 - phone-home
 - final-message
 - power-state-change

# System and/or distro specific settings
# (not accessible to handlers/transforms)
system_info:
   # This will affect which distro class gets used
   distro: debian
   Default user name + that default users groups (if added/used)
   default_user:
     name: debian
     lock_passwd: True
     gecos: Debian
     groups: [adm, audio, cdrom, dialout, dip, floppy, netdev, plugdev, sudo, video]
     sudo: ["ALL=(ALL) NOPASSWD:ALL"]
     shell: /bin/bash
    # Don't forget to add your public key here
     ssh_authorized_keys:
       - ssh-rsa xyz
       - ssh-rsa xyz
   # Other config here will be given to the distro class and/or path classes
   paths:
      cloud_dir: /var/lib/cloud/
      templates_dir: /etc/cloud/templates/
   package_mirrors:
     - arches: [default]
       failsafe:
         primary: https://deb.debian.org/debian
         security: https://deb.debian.org/debian-security
   ssh_svcname: ssh
```

If you don't has `preserve_hostname: false` and `set_hostname` configured, it doesn't work.

**Comment by bpg** [comment] 2024-03-05 23:33
Hey @breakingflower 👋🏼 

I'm not an expert in cloud-init implementation in PVE, but I think if a VM specified a custom user data file (via `user_data_file_id` in the TF template), it overrides the PVE-generated cloud-init, including the hostname that is set from the VM's name.

>I don't use any hostname setting. I'm not sure how I can transfer the value of this name , e.g. k8s-worker-1, to the cloud-init yaml files.

Basically, you'd need to create a custom cloud config for each VM, and set a hostname in there. This can be done by inlining the cloud config files in the resources.


```terraform
resource "proxmox_virtual_environment_vm" "ubuntu_vm" {
  count     = 3
  name      = "test-${count.index}"
  node_name = "pve"

  agent {
    enabled = true
  }

  disk {
    datastore_id = "local-lvm"
    file_id      = proxmox_virtual_environment_download_file.ubuntu_cloud_image.id
    interface    = "virtio0"
    iothread     = true
    discard      = "on"
    size         = 20
  }

  initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    user_data_file_id = proxmox_virtual_environment_file.cloud_config[count.index].id
  }

  network_device {
    bridge = "vmbr0"
  }

}

resource "proxmox_virtual_environment_download_file" "ubuntu_cloud_image" {
  content_type        = "iso"
  datastore_id        = "local"
  node_name           = "pve"
  url                 = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
  overwrite_unmanaged = true
}

data "local_file" "ssh_public_key" {
  filename = "./id_rsa.pub"
}

resource "proxmox_virtual_environment_file" "cloud_config" {
  count        = 3
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "pve"

  source_raw {
    data = <<EOF
#cloud-config
hostname: test-${count.index}
users:
  - default
  - name: ubuntu
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${trimspace(data.local_file.ssh_public_key.content)}
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
    - apt update
    - apt install -y qemu-guest-agent net-tools
    - timedatectl set-timezone America/Toronto
    - systemctl enable qemu-guest-agent
    - systemctl start qemu-guest-agent
    - echo "done" > /tmp/vendor-cloud-init-done
    EOF

    file_name = "cloud-config-${count.index}.yaml"
  }
}

output "vm_ips" {
  value = proxmox_virtual_environment_vm.ubuntu_vm[*].ipv4_addresses
}
```

```
❯ terraform apply -auto-approve
...
SKIP
...

Plan: 7 to add, 0 to change, 0 to destroy.

Changes to Outputs:
  + vm_ips = [
      + (known after apply),
      + (known after apply),
      + (known after apply),
    ]
proxmox_virtual_environment_file.cloud_config[0]: Creating...
proxmox_virtual_environment_file.cloud_config[2]: Creating...
proxmox_virtual_environment_file.cloud_config[1]: Creating...
proxmox_virtual_environment_download_file.ubuntu_cloud_image: Creating...
proxmox_virtual_environment_file.cloud_config[0]: Creation complete after 1s [id=local:snippets/cloud-config-0.yaml]
proxmox_virtual_environment_file.cloud_config[2]: Creation complete after 1s [id=local:snippets/cloud-config-2.yaml]
proxmox_virtual_environment_file.cloud_config[1]: Creation complete after 1s [id=local:snippets/cloud-config-1.yaml]
proxmox_virtual_environment_download_file.ubuntu_cloud_image: Still creating... [10s elapsed]
proxmox_virtual_environment_download_file.ubuntu_cloud_image: Still creating... [20s elapsed]
proxmox_virtual_environment_download_file.ubuntu_cloud_image: Creation complete after 21s [id=local:iso/jammy-server-cloudimg-amd64.img]
proxmox_virtual_environment_vm.ubuntu_vm[2]: Creating...
proxmox_virtual_environment_vm.ubuntu_vm[0]: Creating...
proxmox_virtual_environment_vm.ubuntu_vm[1]: Creating...
...
SKIP
...
proxmox_virtual_environment_vm.ubuntu_vm[0]: Creation complete after 1m16s [id=100]
proxmox_virtual_environment_vm.ubuntu_vm[1]: Still creating... [1m20s elapsed]
proxmox_virtual_environment_vm.ubuntu_vm[2]: Still creating... [1m20s elapsed]
proxmox_virtual_environment_vm.ubuntu_vm[1]: Creation complete after 1m22s [id=102]
proxmox_virtual_environment_vm.ubuntu_vm[2]: Creation complete after 1m23s [id=101]

Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

Outputs:

vm_ips = [
  tolist([
    tolist([
      "127.0.0.1",
    ]),
    tolist([
      "192.168.254.74",
    ]),
  ]),
  tolist([
    tolist([
      "127.0.0.1",
    ]),
    tolist([
      "192.168.254.82",
    ]),
  ]),
  tolist([
    tolist([
      "127.0.0.1",
    ]),
    tolist([
      "192.168.254.164",
    ]),
  ]),
]
❯ ssh ubuntu@192.168.254.164
The authenticity of host '192.168.254.164 (192.168.254.164)' can't be established.
ED25519 key fingerprint is SHA256:TJA0mqATzLUNrJGY46JwW5YohZhfpiGRS3lwT9Wy/NQ.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '192.168.254.164' (ED25519) to the list of known hosts.
Welcome to Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-97-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/pro

  System information as of Tue Mar  5 18:26:26 EST 2024

  System load:  0.51025390625     Processes:             91
  Usage of /:   8.4% of 19.20GB   Users logged in:       0
  Memory usage: 42%               IPv4 address for eth0: 192.168.254.164
  Swap usage:   0%

Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status



The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

ubuntu@test-2:~$ hostname
test-2
ubuntu@test-2:~$

**Comment by breakingflower** [comment] 2024-03-06 10:37
Thanks for the help. 
I tried splitting the conf in 3 files, a vendor file, user file and meta file. The vendor file contains all of the packages / update related things, the user the SSH configuration and the meta the hostname configuration. 

It's unclear to me why using a combination of the above causes either ssh not to work, the hostname not being set or all sorts of undebuggable things.

However, using bpg's comment and rendering it inline works like a charm.
```
resource "proxmox_virtual_environment_file" "ci_k3s_worker_node" {
  count = var.deployment_control_count
  content_type = "snippets"
  datastore_id = "local"
  node_name    = var.virtual_environment_proxmox_node

  source_raw {
    data = <<EOF
#cloud-config
hostname: ${var.deployment_name}-worker-${count.index}
package_update: true
package_upgrade: true
packages: 
  # qemu
  - qemu-guest-agent
  - net-tools
  # nfs
  - nfs-common
users:
  - default
  - name: k3s
    groups:
      - sudo
    shell: /bin/bash
    ssh_authorized_keys:
        - <keys>
    sudo: ALL=(ALL) NOPASSWD:ALL
runcmd:
  # base settings
  - timedatectl set-timezone Europe/Brussels
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  # k3s requires no swap + ufw
  - swapoff -a 
  - ufw disable
  # post
  - reboot
    EOF

    file_name = "ci-${var.deployment_name}-worker-${count.index}.yaml"
  }
}

resource "proxmox_virtual_environment_vm" "k3s_worker" {
    ...
      initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
    user_data_file_id = proxmox_virtual_environment_file.ci_k3s_worker_node[count.index].id
  } 
```

I now have the same files twice, with the only difference being that one is a 'worker' and one is a 'control' node. The specs of the machine, network devices, ... are all the same. is there a way to templatize this?

**Comment by bpg** [comment] 2024-03-09 22:45
Well, if we use only `vendor` data along with the `initialization` block, the VM got configured properly. Here is another test:

```terraform
resource "proxmox_virtual_environment_vm" "testbox" {
  node_name = "pve"
  name      = "testbox"

  agent {
    enabled = true
  }

  cpu {
    type  = "x86-64-v2-AES"
    cores = 2
  }

  memory {
    dedicated = 2048
  }

  disk {
    datastore_id = "local-lvm"
    file_id      = var.ubuntu_cloud_image_id
    interface    = "virtio0"
    iothread     = true
    discard      = "on"
    size         = 32
  }

  initialization {
    datastore_id = "local-lvm"
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }

    user_account {
      keys     = [var.key]
      username = "ubuntu"
    }

    vendor_data_file_id = proxmox_virtual_environment_file.testbox_cloud_config.id
  }

  network_device {
    bridge = "vmbr254"
  }

  operating_system {
    type = "l26"
  }
}

resource "proxmox_virtual_environment_file" "testbox_cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "red"

  source_raw {
    data = <<EOF
#cloud-config
package_update: true
package_upgrade: true
packages: 
  - qemu-guest-agent
  - net-tools
runcmd:
  - timedatectl set-timezone America/Toronto
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - ufw disable
  - echo "done" > /tmp/vendor-cloud-init-done
EOF

    file_name = "testbox-cloud-config.yaml"
  }
}
```

With this template I've got `testbox` as the hostname on the VM.

**Comment by bpg** [comment] 2024-03-19 01:53
Hey @breakingflower, I'm going to close this ticket, as it seems there is a path forward for the configuration you'd like to get. Please feel free to reopen if you need more support.

**Closed by bpg** 2024-03-19 01:53 UTC
Labels: :question: question

**Comment by sealbro** [comment] 2024-06-29 15:26
Hi, folk 
Maybe it sample helps somebody set a hostname with a little less routine work.
I used `for_each` to generate unique files in proxmox.

It is how my VM looks like, but with routine to copy value from name with same name in `local.vms`
```tf
resource "proxmox_virtual_environment_vm" "jetbrains_ubuntu_vm" {
  node_name = "pve"
  vm_id     = 2402

  description = "Managed by Terraform"
  tags        = ["terraform", "ubuntu", "jetbrains"]
  name        = "vm-ubuntu-jetbrains-gateway"
  initialization {
    user_data_file_id = proxmox_virtual_environment_file.for_each_cloud_config["vm-ubuntu-jetbrains-gateway"].id
  }
  # too many other parameters
}
```

`for_each` to genarate cloud config files
```tf
locals {
  vms = tomap({
    "vm-ubuntu-jetbrains-gateway" = <<-EOF
    # some pre- cloud_config data
    ${local.cloud_config_data}
    # some post- cloud_config data
    EOF

    # copy-paste with your VM's hostname
    "some-new-yours-hostname" = <<-EOF
    ${local.cloud_config_data}
    EOF
  })
}

resource "proxmox_virtual_environment_file" "for_each_cloud_config" {
  for_each = local.vms

  content_type = "snippets"
  datastore_id = "local"
  node_name    = "pve"

  source_raw {
    data = <<-EOF
    #cloud-config
    hostname: ${each.key}
    ${each.value}
    EOF

    file_name = "${each.key}-cloud-config.yaml"
  }
}

```

here my default cloud config
```tf
locals {
  cloud_config_data = <<-EOF
  users:
    - name: some_user
      groups:
        - sudo
      shell: /bin/bash
      ssh_authorized_keys:
        - ${trimspace(data.vault_generic_secret.ssh.data["public"])}
      sudo: ALL=(ALL) NOPASSWD:ALL
  package_update: true
  packages:
    - net-tools
    - qemu-guest-agent
  runcmd:
    - [ echo, "Starting... qemu-guest-agent [enable, start]" ]
    - [ systemctl, enable, qemu-guest-agent ]
    - [ systemctl, start, qemu-guest-agent ]
    - [ echo, "Started qemu-guest-agent" ]
  EOF
}
```
