### ISSUE TITLE
failed to determine the IP address of "<node-name>" when using `proxmox_virtual_environment_file`

### ISSUE THREAD

**Issue by spott** [bpg/terraform-provider-proxmox#126] opened 2022-09-19 21:33 UTC
**Describe the bug**
When using `proxmox_virtual_environment_file` resources, the `node_name` doesn't seem to resolve.  When using `Proxmox_virtual_environment_vm` resources, the `node_name` works fine.

**To Reproduce**
Not sure what precisely about my environment is making this happen, but I currently don't have a dns server locally (I'm actually building the vm to host that with this at the moment) which might be causing this issue.

The following file will reproduce:
```
terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
      version = "0.6.1"
    }
    cloudinit = {
      source = "hashicorp/cloudinit"
      version = "2.2.0"
    }
  }
}

provider "proxmox" {
  virtual_environment {
    endpoint = var.proxmox_endpoint
    username = var.proxmox_username
    insecure = true
  }
}


resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = "local"
  node_name    = "moneta"

  source_raw {
    data = "blah"
    file_name = "cloud-config.yaml"
  }
}
```

**Expected behavior**
The file to get created

**Comment by spott** [comment] 2022-09-20 23:57
Note:  If the node_name is changed to an IP address, I get the following error:

`error: Received an HTTP 596 response - Reason: tls_process_server_certificate: certificate verify failed`

**Comment by bpg** [comment] 2022-09-21 00:49
Thanks for the report. Just a quick sanity check -- I don't see the `password` field is being set in the `virtual_environment` section. Is it simply omitted in the example here, or is actually missing in the template?

**Comment by spott** [comment] 2022-09-21 20:51
It is missing in the template and is instead set by an environment variable.

**Comment by spott** [comment] 2022-09-21 21:16
Also note: I've gotten the package to create a vm (so the login works for the API), I just can't get it to build a file.

**Comment by spott** [comment] 2022-09-21 22:26
So, since submitting this ticket, I have gotten a DNS Server up and running.  It works fine (pinging `moneta` works), however I'm still getting the same problem.  (`failed to determine the IP address of node "moneta"`).

Just thought I would throw this out there, as it doesn't appear to be a (management computer) DNS problem.

**Comment by bpg** [comment] 2022-09-28 01:33
Thanks, will take a look in the next few days.

**Comment by bpg** [comment] 2022-09-28 23:30
Hey @spott, unfortunately, I wasn't able to reproduce the issue. My test PVE instance was able to create a file successfully, using your example.

Though in my case the node name `pve` is not resolvable via DNS, but it is set as the host name in the Proxmox configs and at the OS level:

<img width="963" alt="Screen Shot 2022-09-28 at 7 20 40 PM" src="https://user-images.githubusercontent.com/627562/192905453-4d10bf9e-8599-434e-911b-2c5e537183a6.png">

<img width="717" alt="Screen Shot 2022-09-28 at 7 28 31 PM" src="https://user-images.githubusercontent.com/627562/192906114-f36ca613-8962-46f7-a8e5-896f5ccbeaa0.png">

**Comment by spott** [comment] 2022-09-29 21:30
Thanks!  It was the hostname.

Now I get a success from terraform... but no snippet in the snippet directory...  I'm not sure what I'm missing.

Trying to use output blocks to look at `file_name`, `file_tag`, `file_modification_date`, and `file_size` don't show anything, and the task log doesn't show anything either.

When I do a `terraform destroy`, I'm getting a task of "erase data" that says the file doesn't exist.

Any ideas?

**Comment by bpg** [comment] 2022-09-30 00:20
Does you storage (I assume it is `local`?) support "Snippets"? Is the target folder writable? This is how it looks like on my PVE:
 
<img width="1318" alt="Screen Shot 2022-09-29 at 8 16 18 PM" src="https://user-images.githubusercontent.com/627562/193164059-c29b7ab5-16a6-4997-bf1c-cbd985f45a28.png">

**Comment by bpg** [comment] 2022-09-30 00:30
I'm re-tagging this issue as "question", as there seems to be no unexpected behaviour with the provider.

**Comment by spott** [comment] 2022-09-30 00:48
Ok, it looks like that is a permissions issue, though I'm unclear what permissions I need to give.

**Comment by bpg** [comment] 2022-10-17 04:00
@spott I'm going to close this ticket as the original issue (as per title) seems to be  resolved.
You may try to review [installation](https://pve.proxmox.com/pve-docs/chapter-pve-installation.html) and [storage configuration](https://pve.proxmox.com/pve-docs/pve-admin-guide.html#chapter_storage) steps of your PVE environment to see if there is anything missing from the setup.

**Closed by bpg** 2022-10-17 04:00 UTC
Labels: question

**Comment by nrvale0** [comment] 2023-02-23 21:10
I was able to repro this reliably and I was able to get past it by using the FQDN, as opposed to the shortname, of the proxmox server in `node_name` parameter of the file resource.

I'll dive down into the code for that resource and see if I can spot anything obvious though I'm not a golang hacker...

**Comment by nrvale0** [comment] 2023-02-23 23:40
So, it's interesting....using the FQDN gets past the inability to resolve the node_name however it later throws errors during apply in that it fails to verify the TLS cert of the server even if I have told the Provider to not do TLS cert verification:

    Error: received an HTTP 596 response - Reason: tls_process_server_certificate: certificate verify failed

**Comment by nrvale0** [comment] 2023-02-23 23:47
I got as far as seeing how the node_name is packed/unpacked as a schema item. It looks to me like the schema stuff comes from the HashiCorp SDK plugin but I didn't see anything there to suggest that that SDK would care about shortnames v FQDNs. 

Not sure how to proceed except to say I can repro this very reliably.

**Comment by bpg** [comment] 2023-02-23 23:49
Hey @nrvale0, I _suspect_ the " failed to determine the IP address" error is coming from this function https://github.com/bpg/terraform-provider-proxmox/blob/fcf98102522821c9dfb4534731747233bd627d38/proxmox/virtual_environment_nodes.go#L185

It opens an SSH session with the node by its hostname, which is taken from the `node_name` parameter.
This means that this node's short hostname must resolve to an IP from the machine you're running terrafrom on.

Could you check if you can, for example, ping the proxmox host by its short name from this machine? If not, check `hostname -d` output on this machine. If it is empty, you may need to add your domain name to `/etc/resolv.conf` (or similar, whichever is appropriate for your OS)

**Comment by nrvale0** [comment] 2023-02-24 01:29
The Proxmox server name resolves as shortname and FQDN. I even did a packet dump of the DNS traffic, noticed that there was some IPv6 going on, and disabled IPv6 on all nodes and the switch/router just to reduce the possible variables. 

I need to do a packet dump of the TF apply traffic to rule out a resolution problem there since I think I recall golang has its own resolver library it favors over the one in the OS.

My network uses a TLD that is not an official TLD so... ? It's weird that other resources with the same node_name specified don't seem to have any issues.

**Comment by nrvale0** [comment] 2023-02-24 03:12
Just confirming that DNS capture during TF apply with both shortname and FQDN come back clean, correct, and with no intermediate errors but end result is still "failed to determined..."

**Comment by nrvale0** [comment] 2023-02-24 03:20
> It opens an SSH session with the node by its hostname, which is taken from the node_name parameter.

Can you elaborate on this? The TF Provider makes an SSH connection to the Proxmox **server**? I'm trying to think of scenario where I would expect that to happen.

Connecting to the client  for, say, cloud-init or an TF provisioner run ... those scenarios sort of fit with my expectations.

**Comment by nrvale0** [comment] 2023-02-24 03:49
Nevermind, I found it. : https://github.com/bpg/terraform-provider-proxmox/blob/main/proxmox/virtual_environment_datastores.go#L237

**Comment by bpg** [comment] 2023-02-25 03:10
Could you also run with `TF_DEBUG=1 terraform apply ...` and attach the log?

**Comment by nrvale0** [comment] 2023-02-25 19:56
Sure. Two files below. The file names describe the scenario but basically using shortname and FQDN. When I saw that it "works" with FQDN I mean that it was able to at least resolve the host and connect to it but as you can see it failed because it was upset that the FQDN was not present in TLS certificate. But that's at least further than it gets with shortname.

I did not provide output showing that both names resolve because it exposes a bit too much information about internal network. I guess you'll have to trust my nslookup/dig/host skills. ;)

- [tf-shortname-apply.log](https://github.com/bpg/terraform-provider-proxmox/files/10832184/tf-shortname-apply.log)
- 
- [tf-fqdn-apply.log](https://github.com/bpg/terraform-provider-proxmox/files/10832185/tf-fqdn-apply.log)

Also, re previous comments about it being weird that some resources with specified node_name worked while others did not...that makes a lot more sense if there's an SSH going on when creating ..._environment_file resource.

**Comment by bpg** [comment] 2023-02-26 03:20
OK, DNS was a red herring, the issue is related to the way the provider determines the node IP when it opens SSH. It doesn't do a DNS lookup, but rather calls proxmox API `/nodes/<node>/network` to list node's network devices and get the IP from there.

https://github.com/bpg/terraform-provider-proxmox/blob/853f5b9fa9630e4ad33e6c0ab7286b38e42e4ade/proxmox/virtual_environment_nodes.go#L63-L79

So, for some reason it either gets back an empty list, or adapter(s) has no IP4s set. The former could be a permission issue, the latter seems quite possible for DHCP-assigned IPs. Could you pls double check that?

**Comment by nrvale0** [comment] 2023-02-26 17:58
1) First, appreciate your eyes on this. :D

2) It's going to take me a minute but I will get some curls against the API and try to correlate that with logs and share them. The `/nodes/<node>/network thing is interesting` because I not only have a few interfaces in that server but I have quite a few VLANs as well. 

Please stay tuned...

**Comment by kunleoladimeji** [comment] 2023-12-02 23:06
I encountered the same error today:

```
Error: failed to find node endpoint: failed to determine the IP address of node "pve-1"
```

I have verified that DNS for the hostname works from both Proxmox and also my local dev machine.

Could it be that there is no check if the interface is active? I am certain that all the active interfaces can resolve the hostname fine.

Here's my current network config.
```
root@pve-1:/var/lib/vz# pvesh get /nodes/pve-1/network
┌────────┬───────────┬───────────┬─────────────────┬────────────┬─────────────────────────────────────────┬────────┬──────────┬─────────────────┬────────┬─────────┬──────────┬─────────┐
│ active │ autostart │ bridge_fd │ bridge_ports    │ bridge_stp │ comments                                │ exists │ families │ iface           │ method │ method6 │ priority │ type    │
╞════════╪═══════════╪═══════════╪═════════════════╪════════════╪═════════════════════════════════════════╪════════╪══════════╪═════════════════╪════════╪═════════╪══════════╪═════════╡
│        │           │           │                 │            │                                         │        │ ["inet"] │ wlp1s0          │ manual │ manual  │ 5        │ unknown │
├────────┼───────────┼───────────┼─────────────────┼────────────┼─────────────────────────────────────────┼────────┼──────────┼─────────────────┼────────┼─────────┼──────────┼─────────┤
│ 1      │ 1         │           │                 │            │ Management Interface                    │ 1      │ ["inet"] │ enp2s0          │ manual │ manual  │ 3        │ eth     │
├────────┼───────────┼───────────┼─────────────────┼────────────┼─────────────────────────────────────────┼────────┼──────────┼─────────────────┼────────┼─────────┼──────────┼─────────┤
│ 1      │ 1         │           │                 │            │ Bridge Interface for VMs and Containers │ 1      │ ["inet"] │ enx207bd24f48a2 │ manual │ manual  │ 4        │ eth     │
├────────┼───────────┼───────────┼─────────────────┼────────────┼─────────────────────────────────────────┼────────┼──────────┼─────────────────┼────────┼─────────┼──────────┼─────────┤
│ 1      │ 1         │ 0         │ enx207bd24f48a2 │ off        │ VM Bridge                               │        │ ["inet"] │ vmbr0           │ manual │ manual  │ 6        │ bridge  │
└────────┴───────────┴───────────┴─────────────────┴────────────┴─────────────────────────────────────────┴────────┴──────────┴─────────────────┴────────┴─────────┴──────────┴─────────┘```

**Comment by kunleoladimeji** [comment] 2023-12-05 04:13
Thanks for the clear explanation.

I'll update the Proxmox interface to reflect the static IP of the management interface and retry.

**Comment by kunleoladimeji** [comment] 2023-12-05 11:01
Added a static IP to the management interface and works fine!
