### ISSUE TITLE
VM Disks are getting reordered on apply causing VM re-creation

### ISSUE THREAD

**Issue by bpg** [bpg/terraform-provider-proxmox#185] opened 2022-12-13 23:26 UTC
**Describe the bug**
If VM has multiple disks defined, applying the same template second time may cause VM recreation, as provider thinks that the disks have changed.

**To Reproduce**
1. Define a VM template with multiple disks, for example
```
  disk {
    datastore_id = local.datastore_id
    file_id      = proxmox_virtual_environment_file.ubuntu_cloud_image.id
    interface    = "virtio0"
    iothread     = true
  }

  disk {
    datastore_id = local.datastore_id
    interface    = "scsi0"
    discard      = "on"
    ssd          = true
  }

  disk {
    datastore_id = "nfs"
    interface    = "scsi1"
    discard      = "ignore"
    file_format  = "raw"
  }
``` 
2. Apply the template with `terraform apply`
3. Without any changes to the template, run apply again
4. Notice that terraform detected changes in the template:
<img width="874" alt="Screenshot 2022-12-13 at 6 01 22 PM" src="https://user-images.githubusercontent.com/627562/207465672-e221a990-3a88-43cd-9c3f-1fcac5101dbf.png">

**Expected behavior**
A second apply of the template without any changes should cause no-op from terraform.

**Additional context**
Order of disks in PVE UI after appy:
<img width="796" alt="Screenshot 2022-12-13 at 6 17 45 PM" src="https://user-images.githubusercontent.com/627562/207465997-d4356aba-6b18-4528-be1b-178d329d697b.png">
This seems to be a reason for the mismatch.

**Workaround**
Manually re-order disks in the template to match the order expected by PVE (alphabetically by interface name)

**Comment by zarinbal** [comment] 2023-12-31 12:56
Hello,

I've encountered an issue with the Terraform Proxmox provider when adding or removing disks to a template.

**Steps to Reproduce**:
1. **Initial Configuration**: Add two disks to the template as follows:
   ```terraform
   # Disk 1: Boot
   disk {
     datastore_id = "fast"
     discard = "on"
     file_format = "raw"
     file_id = "shared-iso:iso/ubuntu-22.04-cloudimg-amd64-raw.img"
     interface = "scsi0"
     iothread = false
     size = 20
     ssd = true
   }
   # Disk 2: Data
   disk {
     cache = "none"
     datastore_id = "fast"
     discard = "on"
     file_format = "raw"
     interface = "scsi1"
     iothread = false
     size = 15
     ssd = true
   }``` 


2.  **Adding a Third Disk**: 
When I add a third disk (scsi2) , similar to the above configuration, the issue occurs.

**Observed Behavior:**
When adding a third disk, the template behaves unexpectedly. (See attached screenshot): 

![image](https://github.com/bpg/terraform-provider-proxmox/assets/13283304/9e80fd7e-a381-4a07-ad4e-666b7c1de07c)

3.  **Removing a  Disk**: 
Attempting to remove a disk (e.g., the second disk) results in the template trying to recreate itself instead of just removing the specified disk. (See attached screenshot: 

![image](https://github.com/bpg/terraform-provider-proxmox/assets/13283304/baa04875-88c4-4ea6-87ae-f2806da6b518)

**Expected Behavior:**
    The template should allow adding or removing a specified disk without attempting to recreate the entire template.

I'm unsure whether to open a new issue for this or if it fits within the scope of the current one. Additionally, I'm willing to assist in resolving this issue; any guidance on contributing would be greatly appreciated.

Thank you

**Comment by bpg** [comment] 2024-01-03 02:50
Still reproducible (i think 🤔)

**Comment by luis-guimaraes-exoawk** [comment] 2024-04-11 14:04
Any news regarding this? It's really annoying

**Comment by bpg** [comment] 2024-04-15 15:46
I've spent quite a lot of time trying to debug this issue and applying the "consistent order" approach used in the "numa feature" referenced above. No luck so far, and the situation is really messy. 

Terraform does not _always_ return the list of `disk` elements from it state (i.e. on refresh) in a consistent order. Once in a while those items got re-ordered, and stop matching the order defined in the plan. The provider uses this order of items from the state when reading the disc info back from PVE to create a representation of the current remote state.
Then Terraform matches these remote state with the planned state to check if there is any difference. 

The reordering won't be a big problem, as we can "custom diff" and ignore the order. Except, there is a computed attribute `path_in_datastore` in the disks. If its value is missing in the plan (and and the planned state), Terraform uses the one that was previously stored in state. But if the order changes (as above) the "previous" value becomes the one from a different disk 🤦🏼

**Comment by bpg** [comment] 2024-04-15 17:02
Ended up just excluding `path_in_datastore` from comparison in the diff suppress function

**Comment by luis-guimaraes-exoawk** [comment] 2024-04-15 17:10
Thanks for the work on this issue @bpg. Just to give my two cents:

That seems like the best possible way to solve this right now.
As even when we write the map alphabetically, sometimes the `path_in_datastore` value still changes and forces a replacement. 

Does the `path_in_datastore` change due to Terraform or Proxmox?

**Comment by bpg** [comment] 2024-04-15 20:41
> Edit 2: Sorry if I'm stating something obvious you already tried. Is there no way to sort the Terraform state output before comparing it to the state from Proxmox?

It is more about about the _planned_ state. The current code (before the fix) is actually sorting the disks before storing them into the local state. But planned state handling is completely on the Terraform's side, not the provider's. So it gets the current "remote" state from the provider (we read it from PVE and have full control on how disks are ordered there), then calculates the "planned" state using the plan and the stored state, and then compares them. That calculation of the planned state is fully on the Terraform side, and provider has no control over it (on purpose, i guess).

**Comment by bpg** [comment] 2024-05-12 20:37
The issue is still reproducible, see more details in https://github.com/bpg/terraform-provider-proxmox/pull/1215#issuecomment-2103942810

**Comment by AtaLuZiK** [comment] 2024-05-13 05:36
@bpg Maybe need ordered interfaces here?
I checked the Go documentation and maps.Keys may return unordered results（[https://pkg.go.dev/golang.org/x/exp/maps#Keys](https://pkg.go.dev/golang.org/x/exp/maps#Keys)）
[disk.go#L628C4-L628C14](https://github.com/bpg/terraform-provider-proxmox/blob/73d01e754380b24640a3f4c4f0d631de25ebe630/proxmoxtf/resource/vm/disk/disk.go#L628C4-L628C14)

`
	if !isClone || len(currentDiskList) > 0 {
		var diskList []interface{}

		if len(currentDiskList) > 0 {
			resMap := utils.MapResourceList(currentDiskList, mkDiskInterface)
			interfaces := maps.Keys[map[string]interface{}](resMap)
			sort.Strings(interfaces)  // <-- I always get the right result by adding this line
			diskList = utils.OrderedListFromMapByKeyValues(diskMap, interfaces)
		} else {
			diskList = utils.OrderedListFromMap(diskMap)
		}

		err := d.Set(MkDisk, diskList)
		diags = append(diags, diag.FromErr(err)...)
	}
`

**Comment by bpg** [comment] 2024-05-15 02:21
Sorting in that place breaks another use case when adding a new disk out of order of disk interfaces. The `MapResourceList` implementation has diverged from its original design, which introduced this sorting instability. The func shouldn't return a map, but rather a list of the key attribute values (interface values in this case) in the order of the original list.

**Comment by bpg** [comment] 2024-05-15 02:31
@all-contributors please add @AtaLuZiK for testing, ideas

**Closed** 2024-05-15 02:31 UTC
Labels: :bug: bug
