### ISSUE TITLE
Support for passthrough physical disks

### ISSUE THREAD

**Issue by VerwaerdeWim** [bpg/terraform-provider-proxmox#473] opened 2023-08-08 21:53 UTC
**Is your feature request related to a problem? Please describe.**
It's not possible to add physical disk to the proxmox_virtual_environment_vm resource. The disk argument does not accept a physical disk unless I'm mistaken.
 
I use the following command on the pve host to get around this: `qm set <vm-id> -scsi1 /dev/disk/by-id/<disk-id>,backup=0`

This works but then I can no longer make adjustments to the terraform plan. I then get the following error: `Error: error retrieving files from datastore /dev/disk/by-id/<disk-id>: received an HTTP 501 response - Reason: Method 'GET /nodes/pve/storage//dev/disk/by-id/<disk-id>/content' not implemented`

**Describe the solution you'd like**
Adding passthrough physical disks to the proxmox_virtual_environment_vm resource.

**Describe alternatives you've considered**
Currently I avoid the problem by removing the physical disk before making a change to the terraform plan. And remounting the physical disk when the terraform change is done. This is just a minor hassle as I automate this process. However, this feature request would be a cleaner solution.

**Comment by otopetrik** [comment] 2023-10-07 02:40
Please try #606 (in a safe testing environment on non-important data).

The following:
```terraform
disk {
  datastore_id = ""
  path_in_datastore  = "/dev/path/to/block/device"
}
```
could work, setting a `size` value may be required.

**Comment by bpg** [comment] 2023-12-29 18:47
I'm marking this as closed with @606
@VerwaerdeWim please feel free to reopen if it does not work for your use case.

**Closed by bpg** 2023-12-29 18:47 UTC
Labels: :sparkles: enhancement, :pray: help wanted

**Comment by theeternalrat** [comment] 2024-01-01 22:12
I am attempting to follow this issue for disk passthrough. I've configured by disk block like @otopetrik has indicated. The VM will create, but it cannot start as additional arguments are getting added to the config file. 

Here are two config lines from my testing:

```
scsi1: /dev/disk/by-id/id,cache=none,discard=ignore,format=qcow2,iothread=0,size=953G,ssd=0
```

vs 

```
scsi1: /dev/disk/by-id/id,size=1000171864K
```

The bottom configuration is from manually running the attach command `qm set <vm_id> -scsi1 /dev/disk/by-id/id`. The top configuration is what it written to disk after applying terraform. The error message given is: 
```
kvm: -drive file=/dev/disk/by-id/id,if=none,id=drive-scsi1,cache=none,discard=ignore,format=qcow2,aio=io_uring,detect-zeroes=on: Image is not in qcow2 format
TASK ERROR: start failed: QEMU exited with code 1
```

It seems that the issue is the `format` option. I cannot figure out any way to have it ignored through the terraform configuration. Manually removing the `format=qcow2` allows the VM to start as expected.

**Comment by otopetrik** [comment] 2024-01-02 07:37
> It seems that the issue is the `format` option. I cannot figure out any way to have it ignored through the terraform configuration. Manually removing the `format=qcow2` allows the VM to start as expected.

Sorry, forgot that the default format is `qcow2`, my example was missing `file_format` attribute.
This should work:
```
disk {
  datastore_id = ""
  path_in_datastore  = "/dev/path/to/block/device"
  file_format = "raw"
}
```

**Comment by theeternalrat** [comment] 2024-01-03 22:43
That works, thank you very much @otopetrik !
