### ISSUE TITLE
Cannot use cloudinit with initialization 

### ISSUE THREAD

**Issue by paradoxisme** [bpg/terraform-provider-proxmox#1263] opened 2024-05-06 11:03 UTC
**Describe the bug**
I try to create a vm resource based on debian bookworm. The image is correctly downloaded into proxmox, but the provisionning in inilialization has an error.

**To Reproduce**

1. Create a resource : 
  ```
 resource "proxmox_virtual_environment_vm" "debian_bookworm_vm" {
  name      = "${var.vm_hostname}.${var.domain}"
  description = "Managed by Terraform"
  tags        = ["terraform", "debian"]

  node_name = var.node_name
  vm_id     = 4321
  cpu{
    type    = "kvm64"
    cores   = 1
    units   = 1024
  }
  initialization {
    user_data_file_id = proxmox_virtual_environment_file.cloud_config.id
  }
  network_device {
    bridge = "vmbr1"
  }
  disk {
    datastore_id = var.datastore_id
    file_id      = proxmox_virtual_environment_download_file.release_debian_12_bookworm_qcow2_img.id
    interface    = "sata0"
  }
  operating_system {
    type = "l26"
  }
}
```
3. Run 'terraform apply'
```
2024-05-06T12:34:01.102+0200 [ERROR] provider.terraform-provider-proxmox_v0.55.0: Response contains error diagnostic: @module=sdk.proto tf_req_id=f723da27-d405-d516-ffb6-36b89951f1c9 tf_rpc=ApplyResourceChange diagnostic_detail="" diagnostic_severity=ERROR diagnostic_summary="error creating VM: received an HTTP 400 response - Reason: Parameter verification failed. (ciupgrade: property is not defined in schema and the schema does not allow additional properties)" tf_proto_version=6.4 @caller=github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/diag/diagnostics.go:58 tf_provider_addr=registry.terraform.io/bpg/proxmox tf_resource_type=proxmox_virtual_environment_vm timestamp="2024-05-06T12:34:01.102+0200"
2024-05-06T12:34:01.107+0200 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2024-05-06T12:34:01.107+0200 [ERROR] vertex "proxmox_virtual_environment_vm.debian_bookworm_vm" error: error creating VM: received an HTTP 400 response - Reason: Parameter verification failed. (ciupgrade: property is not defined in schema and the schema does not allow additional properties)
```
6. Modify the resource ' "proxmox_virtual_environment_vm" "debian_bookworm_vm"'
   comment this section :   
```
#initialization {
#    user_data_file_id = proxmox_virtual_environment_file.cloud_config.id
# }
```

8. Run 'terraform apply'
The vm is created  but not provisionning

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl

resource "proxmox_virtual_environment_download_file" "release_debian_12_bookworm_qcow2_img" {
  content_type       = "iso"
  datastore_id       = var.datastore_id
  node_name          = var.node_name
  file_name          = "debian-12-generic-amd64.img"
  url                = "https://cloud.debian.org/images/cloud/bookworm/20240429-1732/debian-12-genericcloud-amd64-20240429-1732.qcow2"
  checksum           = "6cc752d71b390c7fea64b0b598225914a7f4adacd4a33fa366187fac01094648628e0681a109ae9320b9a79aba2832f33395fa13154dad636465b7d9cdbed599"
  checksum_algorithm = "sha512"
}


resource "proxmox_virtual_environment_vm" "debian_bookworm_vm" {
  name      = "${var.vm_hostname}.${var.domain}"
  description = "Managed by Terraform"
  tags        = ["terraform", "debian"]

  node_name = var.node_name
  vm_id     = 4321
  cpu{
    type    = "kvm64"
    cores   = 1
    units   = 1024
  }

  initialization {
    user_data_file_id = proxmox_virtual_environment_file.cloud_config.id
  }

  network_device {
    bridge = "vmbr1"
  }

  disk {
    datastore_id = var.datastore_id
    file_id      = proxmox_virtual_environment_download_file.release_debian_12_bookworm_qcow2_img.id
    interface    = "sata0"
  }

  operating_system {
    type = "l26"
  }
}

resource "tls_private_key" "debian_vm_key" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

output "debian_vm_private_key" {
  value     = tls_private_key.debian_vm_key.private_key_pem
  sensitive = true
}

output "debian_vm_public_key" {
  value = tls_private_key.debian_vm_key.public_key_openssh
}

resource "proxmox_virtual_environment_file" "cloud_config" {
  content_type = "snippets"
  datastore_id = var.datastore_id
  node_name    = var.node_name

  source_raw {
    data = <<EOF
#cloud-config
chpasswd:
  list: |
    ubuntu:example
  expire: false
hostname: k8s.local
packages:
  - qemu-guest-agent
users:
  - default
  - name: debian
    groups: debian
    shell: /bin/bash
    ssh-authorized-keys:
      - ${trimspace(tls_private_key.debian_vm_key.public_key_openssh)}
    sudo: ALL=(ALL) NOPASSWD:ALL
EOF

    file_name = "example.cloud-config.yaml"
  }
}
```

**Expected behavior**
The VM is provionning with cloudinit

**Additional context**

- Single or clustered Proxmox: single
- Proxmox version: 7.4-17
- Provider version (ideally it should be the latest version): 0.55.0
- Terraform/OpenTofu version:
- Terraform v1.8.2 on linux_amd64
+ provider registry.terraform.io/bpg/proxmox v0.55.0
+ provider registry.terraform.io/hashicorp/local v2.5.1
+ provider registry.terraform.io/hashicorp/null v3.2.2
+ provider registry.terraform.io/hashicorp/random v3.6.1
+ provider registry.terraform.io/hashicorp/tls v4.0.5
- OS (where you run Terraform/OpenTofu from):
- Debug logs (`TF_LOG=DEBUG terraform apply`):
```
proxmox_virtual_environment_vm.debian_bookworm_vm: Creating...
2024-05-06T12:34:01.031+0200 [INFO]  Starting apply for proxmox_virtual_environment_vm.debian_bookworm_vm
2024-05-06T12:34:01.033+0200 [DEBUG] proxmox_virtual_environment_vm.debian_bookworm_vm: applying the planned Create change
2024-05-06T12:34:01.039+0200 [DEBUG] provider.terraform-provider-proxmox_v0.55.0: [DEBUG] setting computed for "network_interface_names" from ComputedKeys
2024-05-06T12:34:01.039+0200 [DEBUG] provider.terraform-provider-proxmox_v0.55.0: [DEBUG] setting computed for "ipv6_addresses" from ComputedKeys
2024-05-06T12:34:01.040+0200 [DEBUG] provider.terraform-provider-proxmox_v0.55.0: [DEBUG] setting computed for "ipv4_addresses" from ComputedKeys
2024-05-06T12:34:01.041+0200 [DEBUG] provider.terraform-provider-proxmox_v0.55.0: [DEBUG] setting computed for "mac_addresses" from ComputedKeys
2024-05-06T12:34:01.044+0200 [DEBUG] provider.terraform-provider-proxmox_v0.55.0: Sending HTTP Request: @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/logging/logging_http_transport.go:162 Content-Type=application/x-www-form-urlencoded tf_http_req_uri=/api2/json/nodes/XXXXX/qemu @module=proxmox Accept-Encoding=gzip Host=XXXXX.lan:8006 User-Agent=Go-http-client/1.1 tf_http_req_body="acpi=1&agent=enabled%3D0%2Cfstrim_cloned_disks%3D0%2Ctype%3Dvirtio&balloon=0&bios=seabios&boot=order%3Dsata0%3Bnet0&cicustom=user%3Dhome%3Asnippets%2Fexample.cloud-config.yaml&ciupgrade=1&cores=1&cpu=cputype%3Dkvm64&cpuunits=1024&description=Managed+by+Terraform&ide2=file%3Dlocal-lvm%3Acloudinit%2Cmedia%3Dcdrom%2C&keyboard=en-us&memory=512&name=k8s.terraform.local&net0=model%3Dvirtio%2Cbridge%3Dvmbr1%2Cfirewall%3D0&numa=0&onboot=1&ostype=l26&protection=0&scsihw=virtio-scsi-pci&sockets=1&tablet=1&tags=debian%3Bterraform&template=0&vga=memory%3D16%2Ctype%3Dstd&vmid=4321" tf_http_req_method=POST tf_http_trans_id=d4ba4f61-6082-b37b-7a58-a77af14845c2 tf_provider_addr=registry.terraform.io/bpg/proxmox Accept=application/json Authorization="PVEAPIToken=terraform-prov@pve!d833a82c-0ac4-11ef-98ad-0f84d6bb6b6a=6bc0c06b-b3ed-4a52-b8ee-63a6eb3d2436" Content-Length=574 tf_mux_provider=tf5to6server.v5tov6Server tf_req_id=f723da27-d405-d516-ffb6-36b89951f1c9 tf_resource_type=proxmox_virtual_environment_vm tf_http_op_type=request tf_http_req_version=HTTP/1.1 tf_rpc=ApplyResourceChange timestamp="2024-05-06T12:34:01.043+0200"
2024-05-06T12:34:01.102+0200 [DEBUG] provider.terraform-provider-proxmox_v0.55.0: Received HTTP Response: Date="Mon, 06 May 2024 10:41:33 GMT" Expires="Mon, 06 May 2024 10:41:33 GMT" Content-Length=124 Content-Type=application/json;charset=UTF-8 Server=pve-api-daemon/3.0 tf_http_res_status_reason="400 Parameter verification failed." tf_http_trans_id=d4ba4f61-6082-b37b-7a58-a77af14845c2 tf_mux_provider=tf5to6server.v5tov6Server tf_provider_addr=registry.terraform.io/bpg/proxmox Cache-Control=max-age=0 tf_resource_type=proxmox_virtual_environment_vm tf_rpc=ApplyResourceChange tf_http_op_type=response tf_http_res_status_code=400 tf_http_res_version=HTTP/1.1 Pragma=no-cache tf_http_res_body="{\"errors\":{\"ciupgrade\":\"property is not defined in schema and the schema does not allow additional properties\"},\"data\":null}" tf_req_id=f723da27-d405-d516-ffb6-36b89951f1c9 @caller=github.com/hashicorp/terraform-plugin-sdk/v2@v2.33.0/helper/logging/logging_http_transport.go:162 @module=proxmox timestamp="2024-05-06T12:34:01.102+0200"
2024-05-06T12:34:01.102+0200 [ERROR] provider.terraform-provider-proxmox_v0.55.0: Response contains error diagnostic: @module=sdk.proto tf_req_id=f723da27-d405-d516-ffb6-36b89951f1c9 tf_rpc=ApplyResourceChange diagnostic_detail="" diagnostic_severity=ERROR diagnostic_summary="error creating VM: received an HTTP 400 response - Reason: Parameter verification failed. (ciupgrade: property is not defined in schema and the schema does not allow additional properties)" tf_proto_version=6.4 @caller=github.com/hashicorp/terraform-plugin-go@v0.22.2/tfprotov6/internal/diag/diagnostics.go:58 tf_provider_addr=registry.terraform.io/bpg/proxmox tf_resource_type=proxmox_virtual_environment_vm timestamp="2024-05-06T12:34:01.102+0200"
2024-05-06T12:34:01.107+0200 [DEBUG] State storage *statemgr.Filesystem declined to persist a state snapshot
2024-05-06T12:34:01.107+0200 [ERROR] vertex "proxmox_virtual_environment_vm.debian_bookworm_vm" error: error creating VM: received an HTTP 400 response - Reason: Parameter verification failed. (ciupgrade: property is not defined in schema and the schema does not allow additional properties)
╷
│ Error: error creating VM: received an HTTP 400 response - Reason: Parameter verification failed. (ciupgrade: property is not defined in schema and the schema does not allow additional properties)
│ 
│   with proxmox_virtual_environment_vm.debian_bookworm_vm,
│   on resource.tf line 12, in resource "proxmox_virtual_environment_vm" "debian_bookworm_vm":
│   12: resource "proxmox_virtual_environment_vm" "debian_bookworm_vm" {
│ 
╵
2024-05-06T12:34:01.118+0200 [DEBUG] provider.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = error reading from server: EOF"
2024-05-06T12:34:01.120+0200 [DEBUG] provider: plugin process exited: path=.terraform/providers/registry.terraform.io/bpg/proxmox/0.55.0/linux_amd64/terraform-provider-proxmox_v0.55.0 pid=11119
```

**Comment by bpg** [comment] 2024-05-06 22:01
This seems to be a duplicate of #1252. The other issue is missing an important detail -- this error occurs on PVE v7.x, v8.x is fine.

**Closed** 2024-05-06 23:16 UTC
Labels: :bug: bug
