### ISSUE TITLE
Changing VM property initialization.user_account.keys destroys resource

### ISSUE THREAD

**Issue by michaelfranzl** [bpg/terraform-provider-proxmox#373] opened 2023-06-15 08:23 UTC
Changing the property `initialization.user_account.keys` causes a VM resource to be re-created. This also means losing data.

**Steps to reproduce the behavior**

1. Create a resource `proxmox_virtual_environment_vm` with property `initialization.user_account.keys` set to an array of strings.
2. Run `terraform apply`: The resource is created successfully.
3. Change one of the strings in the array of the property `initialization.user_account.keys`.
4. Run `terraform plan`: The resource would be recreated (destroyed and created again, which means losing data)

**Expected behavior**

Changing the property `initialization.user_account.keys` should not destroy the resource because the SSH keys are applied by _cloud-init_ only at the first boot anyway. In other words, the property can be safely ignored after the initial creation of the resource.

Why would anyone then change this property? It is often practical to not assign literal strings to this property, but a variable which is shared across resources. In other words, a set of SSH keys is maintained in one location (e.g. vars.tf) and then reused in multiple resources to avoid duplication of string literals.

**Additional context**

- Provider version: 0.21.1
- Terraform version: 1.4.5
- OS: Linux

**Comment by bpg** [comment] 2023-08-10 21:25
Thanks for reporting this!
@all-contributors please add @michaelfranzl for bug

**Comment by ratiborusx** [comment] 2023-10-24 16:38
I'm not entirely sure, but it may be related to how Proxmox processes cloud-init cloud-config. You can change some cloud-config parameters in GUI, then regenerate cloud-init image and it's settings will be reapplied immediately. Or after shutdown/startup if you didn't regenerate an image. Even then it's just a meager subset of cloud-init modules that Proxmox exposes (for example no way to install specific packages). Considering that provider uses Proxmox API i'd say it works as intended.
![image](https://github.com/bpg/terraform-provider-proxmox/assets/123507924/9608377b-05a3-4672-bf48-5ae1ab0052e3)

If you wish to ignore any changes to cloud-config you could use "lifecycle" directive in your resource like this:
```
lifecycle {
  ignore_changes = [
    initialization[0].user_account
  ]
}
```
That's how i'm trying to deal with it for now at least.
But i'm also experiencing cloud-init related problems (need to investigate more).

**Comment by jsaalfeld** [comment] 2024-04-05 07:36
We're still experiencing this bug with Proxmox 8.1.4 and provider version 0.51.1 - howecer the `ignore_changes` workaround is still valid.

**Comment by elias314** [comment] 2024-04-05 16:07
I don't think this is a bug or should be fixed based on how Terraform and other providers work.  With the AWS provider for example, changes to `user_data` will cause the `aws_instance` resource to be recreated too, even though user data is only applied on first boot as well.  The provider can't know what the intent was for the change in user data or cloud init, so since it doesn't match and the only way to update it is to recreate the resource, that's what it has to do.

My boilerplate user data for AWS instances gets modified slowly over time and I don't want to recreate my instances for these small de-minimis changes, so once my instance setup is "done", I wrap the `user_data` property in an `ignore_changes` block, just has been done here.  

I'd argue this isn't a bug, but instead the expected pattern and behavior for this type of change based on how Terraform works and other providers behave.  Terraform's main purpose it to make sure the state of the resources it deploys match the codified state for those resources, so seems really awkward and counter to what Terraform is designed to do to have a provider notice a state change but then decide to ignore it.  The `ignore_changes` block was implemented to handle these exact scenarios, and is the correct solution for handling changes to `initialization.user_account.keys` or any other property for which you don't want Terraform to fix.

**Comment by bpg** [comment] 2024-04-07 20:58
Thanks @elias314, well explained!

> The provider can't know what the intent was for the change in user data or cloud init, so since it doesn't match and the only way to update it is to recreate the resource, that's what it has to do.

This pretty much summarizes the logic behind the current behaviour. I'm closing this ticket as "not planned".

**Closed by bpg** 2024-04-07 20:58 UTC
Labels: :bug: bug, wontfix

**Comment by jsaalfeld** [comment] 2024-04-08 04:51
I understand the reasoning and it is fine.

But then the "initialization" block shouldn't be referred to be a "cloud-init" block (https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#initialization). That's what threw me off. If it would be referred to something like "first time setup-block" than it would be more transparent on why it recreates and what the purpose is.

cloud-init would, at maximum, need a reboot.
