### ISSUE TITLE
Error: unknown time zone 

### ISSUE THREAD

**Issue by resnostyle** [bpg/terraform-provider-proxmox#1308] opened 2024-05-17 03:59 UTC
**Describe the bug**
I should be able to set timezones other then UTC . When I attempt to use America/New_York for example I get an unkown time zone error.

**To Reproduce**
```hcl
resource "proxmox_virtual_environment_time" "first_node_time" {
  node_name = "first-node"
  time_zone = "America/New_York"
}
```
```
╷
│ Error: unknown time zone America/New_York
│ 
│   with proxmox_virtual_environment_time.time[0],
│   on proxmox.tf line 65, in resource "proxmox_virtual_environment_time" "time":
│   65: resource "proxmox_virtual_environment_time" "time" {

```
----
As another method for validation I set
```hcl
resource "proxmox_virtual_environment_time" "first_node_time" {
  node_name = "first-node"
  time_zone = "UTC"
}
```
 and applied it, then manaually changed the node configuration to America/New_York, and recieved the same error on the next unchanged terraform plan.

**Expected behavior**
I believe I should be able to set timezones other then UTC. 

**Additional context**

- Single or clustered Proxmox:
- Proxmox version: 8.2.2
- Provider version (ideally it should be the latest version): 0.55.1
- Terraform/OpenTofu version: terraform 1.8.1

**Comment by bpg** [comment] 2024-05-17 21:59
Hi @resnostyle! 👋🏼

I can't really reproduce this issue.
Starting with the template:

```hcl
resource "proxmox_virtual_environment_time" "node_time" {
  node_name = "pve"
  time_zone = "America/Toronto"
}
```
I've got:
```
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  + create

OpenTofu will perform the following actions:

  # proxmox_virtual_environment_time.node_time will be created
  + resource "proxmox_virtual_environment_time" "node_time" {
      + id         = (known after apply)
      + local_time = (known after apply)
      + node_name  = "pve"
      + time_zone  = "America/New_York"
      + utc_time   = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_virtual_environment_time.node_time: Creating...
proxmox_virtual_environment_time.node_time: Creation complete after 0s [id=pve_time]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

Then changed the timezone:
```hcl 
resource "proxmox_virtual_environment_time" "node_time" {
  node_name = "pve"
  time_zone = "America/Toronto"
}
```
```﻿
OpenTofu used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

OpenTofu will perform the following actions:

  # proxmox_virtual_environment_time.node_time will be updated in-place
  ~ resource "proxmox_virtual_environment_time" "node_time" {
        id         = "pve_time"
      ~ time_zone  = "America/New_York" -> "America/Toronto"
        # (3 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  OpenTofu will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

proxmox_virtual_environment_time.node_time: Modifying... [id=pve_time]
proxmox_virtual_environment_time.node_time: Modifications complete after 0s [id=pve_time]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```
![Screenshot 2024-05-17 at 5 55 45 PM](https://github.com/bpg/terraform-provider-proxmox/assets/627562/ebc95df1-a42f-42e1-9169-e6a0344b1178)


Could you possible share your terraform output and perhaps the debug log?

**Comment by bpg** [comment] 2024-05-23 02:08
Hi @resnostyle! Could you provide more details so I'll debug it further?
Otherwise I'm going to close this ticker as "can't reproduce"...

**Comment by bpg** [comment] 2024-05-27 03:23
@resnostyle I'm closing this ticket as "can't reproduce". Feel free to reopen if need more help  with this.

**Closed by bpg** 2024-05-27 03:23 UTC
Labels: :bug: bug, :hourglass: pending author's response, :shrug: can't reproduce
