### ISSUE TITLE
proxmox_virtual_environment_vm cannot be created on Proxmox 8.3 - fails with 501 Not Implemented error

### ISSUE THREAD

**Issue by consi** [bpg/terraform-provider-proxmox#1658] opened 2024-11-26 09:42 UTC
**Describe the bug**
I'm trying to create VM from plan described below:
```
# proxmox_virtual_environment_vm.worker_node["1"] will be created
 + resource "proxmox_virtual_environment_vm" "worker_node" {
     + acpi                    = true
     + bios                    = "seabios"
     + description             = "Node talos-cluster-node-6ea23f5e for Talos K8S cluster talos-cluster"
     + id                      = (known after apply)
     + ipv4_addresses          = (known after apply)
     + ipv6_addresses          = (known after apply)
     + keyboard_layout         = "en-us"
     + mac_addresses           = (known after apply)
     + migrate                 = false
     + name                    = "talos-cluster-node-6ea23f5e"
     + network_interface_names = (known after apply)
     + on_boot                 = true
     + protection              = false
     + reboot                  = false
     + scsi_hardware           = "virtio-scsi-pci"
     + started                 = true
     + stop_on_destroy         = false
     + tablet_device           = true
     + tags                    = [
         + "talos-cluster",
       ]
     + template                = false
     + timeout_clone           = 1800
     + timeout_create          = 1800
     + timeout_migrate         = 1800
     + timeout_move_disk       = 1800
     + timeout_reboot          = 1800
     + timeout_shutdown_vm     = 1800
     + timeout_start_vm        = 1800
     + timeout_stop_vm         = 300
     + vm_id                   = 203
       # (1 unchanged attribute hidden)
     + cdrom {
         + enabled   = true
         + file_id   = "local:iso/talos-v1.8.0-amd64.iso"
         + interface = "ide3"
       }
     + cpu {
         + cores      = 2
         + hotplugged = 0
         + limit      = 0
         + numa       = false
         + sockets    = 1
         + type       = "qemu64"
         + units      = 1024
       }
     + disk {
         + aio               = "io_uring"
         + backup            = true
         + cache             = "writeback"
         + datastore_id      = "hdd"
         + discard           = "ignore"
         + file_format       = (known after apply)
         + interface         = "scsi"
         + iothread          = false
         + path_in_datastore = (known after apply)
         + replicate         = true
         + size              = 10
         + ssd               = false
       }
     + initialization {
         + datastore_id = "local-lvm"
         + upgrade      = (known after apply)
         + dns {
             + servers = [
                 + "172.21.25.166",
               ]
           }
         + ip_config {
             + ipv4 {
                 + address = "172.21.25.184/27"
                 + gateway = "172.21.25.161"
               }
           }
       }
     + memory {
         + dedicated      = 2048
         + floating       = 2048
         + keep_hugepages = false
         + shared         = 0
       }
     + network_device {
         + bridge      = "vmbr0"
         + enabled     = true
         + firewall    = false
         + mac_address = (known after apply)
         + model       = "virtio"
         + mtu         = 0
         + queues      = 0
         + rate_limit  = 0
         + vlan_id     = 10
       }
     + operating_system {
         + type = "l26"
       }
   }
```

It fails with error:

```
 Error: error creating VM: All attempts fail:
 #1: received an HTTP 501 response - Reason: Method 'POST /nodes//qemu' not implemented
 #2: received an HTTP 501 response - Reason: Method 'POST /nodes//qemu' not implemented
 #3: received an HTTP 501 response - Reason: Method 'POST /nodes//qemu' not implemented

   with proxmox_virtual_environment_vm.worker_node["1"],
   on setup_nodes.tf line 16, in resource "proxmox_virtual_environment_vm" "worker_node":
   16: resource "proxmox_virtual_environment_vm" "worker_node" {
```

Request behind that is here:
```
tf_http_req_uri=/api2/json/nodes//qemu tf_provider_addr=registry.terraform.io/bpg/proxmox Accept=application/json tf_http_req_body="acpi=1&agent=enabled%3D0%2Cfstrim_cloned_disks%3D0%2Ctype%3Dvirtio&balloon=2048&bios=seabios&boot=order%3Dide3%3Bnet0&cores=2&cpu=cputype%3Dqemu64&cpuunits=1024&description=Node+talos-cluster-master-6ea23f5e+for+Talos+K8S+cluster+talos-cluster&ide2=file%3Dlocal-lvm%3Acloudinit%2Cmedia%3Dcdrom%2C&ide3=file%3Dlocal%3Aiso%2Ftalos-v1.8.0-amd64.iso%2Cmedia%3Dcdrom%2C&ipconfig0=gw%3D172.21.25.161%2Cip%3D172.21.25.182%2F27&keyboard=en-us&memory=2048&name=talos-cluster-master-6ea23f5e&nameserver=172.21.25.166&net0=model%3Dvirtio%2Cbridge%3Dvmbr0%2Cfirewall%3D0%2Ctag%3D10&numa=0&onboot=1&ostype=l26&protection=0&scsi=file%3Dhdd%3A10%2Cformat%3Dqcow2%2Csize%3D10737418240%2Caio%3Dio_uring%2Cbackup%3D1%2Ciothread%3D0%2Cssd%3D0%2Cdiscard%3Dignore%2Ccache%3Dwriteback%2Creplicate%3D1&scsihw=virtio-scsi-pci&sockets=1&tablet=1&tags=talos-cluster&template=0&vga=memory%3D16%2Ctype%3Dstd&vmid=201"
```

It also tries to delete unreferenced disks on VMs that were never created:
```
tf_http_req_method=DELETE tf_http_req_uri="/api2/json/nodes//qemu/0/?destroy-unreferenced-disks=1&purge=1"
```

Please also provide a minimal Terraform configuration that reproduces the issue.

```hcl
resource "proxmox_virtual_environment_vm" "worker_node" {
    for_each = { for index, node in local.node_names : index => node }
    depends_on = [
        resource.proxmox_virtual_environment_download_file.talos_iso
    ]
    name = each.value
    description = "Node ${each.value} for Talos K8S cluster ${var.cluster_name}"

    tags = [
        var.cluster_name
    ]
    
    node_name = var.setup_node
    
    cdrom {
        file_id = resource.proxmox_virtual_environment_download_file.talos_iso.id
        enabled = true
    }

    cpu {
        cores = var.k8s_nodes[each.key].cpu
    }

    memory {
        dedicated = var.k8s_nodes[each.key].memory.dedicated
        floating = var.k8s_nodes[each.key].memory.floating
    }

    disk {
        datastore_id = var.k8s_nodes[each.key].disk.datastore
        size = var.k8s_nodes[each.key].disk.size
        cache = var.k8s_nodes[each.key].disk.cache != "" ? var.k8s_nodes[each.key].disk.cache : "none"
        interface = "scsi"
    }

    network_device {
        bridge = var.bridge_name
        vlan_id = var.bridge_vlan == "" ? null : var.bridge_vlan
        model = "virtio"
        firewall = "false"
        enabled = true
    } 
    
    initialization {
        ip_config {
            ipv4 {
                address = var.k8s_nodes[each.key].address
                gateway = var.network_gateway
            }
        }
        dns {
            servers = var.network_dns
        }
    }

    operating_system {
        type = "l26"
    }

    started = true
    vm_id = var.proxmox_vmid_offset + length(var.k8s_masters) + each.key
}

```

**Expected behavior**
VM is being created with selected parameters

- Single or clustered Proxmox: single
- Proxmox version: 8.3
- Provider version (ideally it should be the latest version): 0.67.1
- Terraform/OpenTofu version: 1,9,8

**Comment by bpg** [comment] 2024-11-26 13:12
Hey @consi 👋

It looks like `var.setup_node` produces an empty string in your config, which causes an empty `node_name` value.

And apparently we miss a validator for this attribute 🤦

**Comment by bpg** [comment] 2024-12-05 21:46
Hey @consi 👋🏼,

I hope you were able to resolve your issue and that the empty `var.setup_node` was the root cause. I’ll go ahead and close this ticket, but feel free to open a new one if you need further assistance.

**Closed by bpg** 2024-12-05 21:46 UTC
Labels: :bug: bug, :hourglass: pending author's response
